services:
  express-app:
    image: pplx/mystery
    ports:
        - 8080:8080
    container_name: mystery-hello
    
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds</em>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower